export const protectedRoutes = [
  '/create-shop',
  '/admin',
  '/admin/:page',
  '/user',
  '/user/:page',
  '/profile',
];

export const cities = [
  'Barisal',
  'Bogra',
  'Chandpur',
  'Chittagong',
  'Comilla',
  "Cox's Bazar",
  'Dhaka',
  'Dinajpur',
  'Faridpur',
  'Feni',
  'Gaibandha',
  'Gazipur',
  'Gopalganj',
  'Habiganj',
  'Jamalpur',
  'Jessore',
  'Jhalokathi',
  'Jhenaidah',
  'Joypurhat',
  'Khagrachari',
  'Khulna',
  'Kishoreganj',
  'Kurigram',
  'Kushtia',
  'Lakshmipur',
  'Lalmonirhat',
  'Madaripur',
  'Magura',
  'Manikganj',
  'Meherpur',
  'Moulvibazar',
  'Munshiganj',
  'Mymensingh',
  'Naogaon',
  'Narail',
  'Narayanganj',
  'Narsingdi',
  'Natore',
  'Netrokona',
  'Nilphamari',
  'Noakhali',
  'Pabna',
  'Panchagarh',
  'Patuakhali',
  'Pirojpur',
  'Rajbari',
  'Rajshahi',
  'Rangamati',
  'Rangpur',
  'Satkhira',
  'Shariatpur',
  'Sherpur',
  'Sirajganj',
  'Sunamganj',
  'Sylhet',
  'Tangail',
  'Thakurgaon',
];

export const heroImages = [
  {
    id: 1,
    src: '/happyPeople.webp',
    alt: '🌟 Customer Trust',
    title: '🌟 Customer Trust',
    description:
      'Trusted by 10,000+ happy customers — we value your satisfaction and security',
    cta: 'Shop Now',
    link: '/products',
  },
  {
    id: 2,
    src: '/quickDelicery.webp',
    alt: '📦 Fast Delivery',
    title: '📦 Fast Delivery',
    description:
      'Get your products at lightning speed — same-day and next-day delivery available!',
    cta: 'Order Now',
    link: '/products',
  },
  {
    id: 3,
    src: '/onlineOrder.webp',
    alt: '🛒 Easy Shopping Experience',
    title: '🛒 Easy Shopping Experience',
    description:
      'Seamless shopping experience on mobile and desktop — browse, buy, and track easily!',
    cta: 'View Collection',
    link: '/products',
  },
];
